name: example/opsdesk
on:
  push:
    branches:
      - 'ghtest/*'

env:
  PUSH: --push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure ACR
        run: |
          az acr login -n opsdesk
          docker pull opsdesk.azurecr.io/opsdesk/example-har:release-1.5.5
          docker push opsdesk.azurecr.io/opsdesk/example-har:release-1.5.5
